version: '3.5'
services:
    mysql_ema:
        container_name: mysql_ema
        image: mysql:latest
        restart: on-failure
        environment:
            MYSQL_DATABASE: ema_revise
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
          - 3302:3306
        volumes:
          - ./docker/volumes/mysql/data:/var/lib/mysql
    php_ema:
        container_name: php_ema
        build: ./docker/build/php
        tty: true
        depends_on:
            - mysql_ema
        volumes:
          - .:/var/www/ema-revise
    nginx_ema:
        container_name: nginx_ema
        image: nginx:latest
        restart: on-failure
        ports:
          - 8080:80
        volumes:
          - ./:/var/www/ema-revise
          - ./docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php_ema
          - mysql_ema